management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8093
  tomcat:
    threads:
      max: 500

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: aftersale-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  servlet:
    multipart:
      enabled: true
      max-request-size: 10MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/oomall?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF8
    username: dbuser
    password: 12345678
    druid:
      initial-size: 3
      min-idle: 3
      max-active: 10
      max-wait: 60000
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 100
      validation-query: select 1

  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 100
        max-idle: 100
        min-idle: 0
        max-wait: -1
    timeout: 5000


mybatis:
  type-aliases-package: cn.edu.xmu.oomall.aftersale.model.po
  mapper-locations: classpath*:cn.edu.xmu.oomall.aftersale.mapper/*.xml
  configuration:
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
rocketmq:
  name-server: 124.71.31.61:9876
  producer:
    group: aftersale_callback_group
    max-message-size: 4096
    send-message-timeout: 3000

pagehelper:
  helper-dialect: mysql
