management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8091
  tomcat:
    threads:
      max: 500

spring:
  application:
    name: payment-service
  cloud:
    nacos:
      discovery:
        server-addr: 172.16.3.152:8848

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oomall?serverTimezone=GMT%2B8&useSSL=false
    username: dbuser
    password: 12345678
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 3
      min-idle: 3
      max-active: 10
      max-wait: 60000
      stat-view-servlet:
        login-username: admin
        login-password: 123456
        enabled: true
        url-pattern: /druid/*

      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 100
      validation-query: select 1

  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 172.16.0.206
    # Redis服务器连接端口
    port: 6379
    password:
    #连接池最大连接数（使用负值表示没有限制）
    lettuce:
      pool:
        max-active: 100
        max-idle: 100
        min-idle: 0
        max-wait: -1
    timeout: 5000

rocketmq:
  name-server: 172.16.2.101:9876
  producer:
    group: payment_callback_group
    max-message-size: 4096
    send-message-timeout: 3000

mybatis:
  type-aliases-package: cn.edu.xmu.oomall.payment.model.po
  mapper-locations: classpath*:cn.edu.xmu.oomall.payment.mapper/*.xml
  configuration:
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

pagehelper:
  helper-dialect: mysql
